services:
  - type: web
    name: pdf-server
    runtime: python
    buildCommand: apt-get install -y tesseract-ocr tesseract-ocr-ita && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
